config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :comments
  resources :schools
  resources :publishers
  resources :writers
  devise_for :users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
root "home#index"  
end

app/models/writer.rb
class Writer < ApplicationRecord
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :set_writer, only: %i[ show edit update destroy ]

  # GET /writers or /writers.json
  def index
    @writers = Writer.all
  end

  # GET /writers/1 or /writers/1.json
  def show
  end

  # GET /writers/new
  def new
    @writer = Writer.new
  end

  # GET /writers/1/edit
  def edit
  end

  # POST /writers or /writers.json
  def create
    @writer = Writer.new(writer_params)

    respond_to do |format|
      if @writer.save
        format.html { redirect_to writer_url(@writer), notice: "Writer was successfully created." }
        format.json { render :show, status: :created, location: @writer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /writers/1 or /writers/1.json
  def update
    respond_to do |format|
      if @writer.update(writer_params)
        format.html { redirect_to writer_url(@writer), notice: "Writer was successfully updated." }
        format.json { render :show, status: :ok, location: @writer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @writer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1 or /writers/1.json
  def destroy
    @writer.destroy!

    respond_to do |format|
      format.html { redirect_to writers_url, notice: "Writer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_writer
      @writer = Writer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def writer_params
      params.require(:writer).permit(:name)
    end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/_form.html.erb
<%= form_with(model: writer) do |form| %>
  <% if writer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
        <% writer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/writers/_writer.html.erb
<div id="<%= dom_id writer %>">
  <p>
    <strong>Name:</strong>
    <%= writer.name %>
  </p>

</div>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render "form", writer: @writer %>

<br>

<div>
  <%= link_to "Show this writer", @writer %> |
  <%= link_to "Back to writers", writers_path %>
</div>

app/views/writers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Writers</h1>

<div id="writers">
  <% @writers.each do |writer| %>
    <%= render writer %>
    <p>
      <%= link_to "Show this writer", writer %>
    </p>
  <% end %>
</div>

<%= link_to "New writer", new_writer_path %>

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render "form", writer: @writer %>

<br>

<div>
  <%= link_to "Back to writers", writers_path %>
</div>

app/views/writers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @writer %>

<div>
  <%= link_to "Edit this writer", edit_writer_path(@writer) %> |
  <%= link_to "Back to writers", writers_path %>

  <%= button_to "Destroy this writer", @writer, method: :delete %>
</div>